### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kennylbj** [kennylbj/patrick-wechat#4]
The roadmap for patrick-wechat is:

- [x] Bump to Taro V3.

- [ ] Refactor components with react hooks.

- [ ] Release patrick-server as backend server using nest.js.

- [ ] Release patrick-admin based on React/Ant-design-pro for managing questionnaire and result.

- [ ] Login / Logout support.

It will take a few months to implement the features above, but I will release new updates continuously.
